Sentiment analysis is a natural language processing (NLP) task that involves determining the emotional tone, attitude, or opinion expressed in a piece of text

pip install -r name of file inside the venv if all libraries inside specific file

Transformers is a python library developed by hugging face used to load,run and finetune pretrained models(open source AI models). To use open source AI models (no need for internet, can be runned locally and finetune)

 It's a powerful tool used in things like translation, text generation, and question answering.


In [1]:
import transformers

c:\Users\asus\Desktop\LLM\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


pytorch library used in computer vision and NLP

In [2]:
import torch

pipeline in machine learning is just a set of steps that you follow to take data, process it, use a model to learn from it, and then make predictions.

Maybe it needs latest version of transformer and pip and old version of python <11

pip install --upgrade transformers (latest vaersion for transformer)

python -m venv test (for venv)

python -m pip install -- upgrade pip

pip install transformers==4.27.0 torch==1.13.1 Pillow gradio openai polars seaborn scikit-learn

pip install numpy==1.23.5



In [3]:
import torch
import transformers

print(torch.__version__)
print(transformers.__version__)


1.13.1+cpu
4.27.0


In [4]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-sentiment-latest")





c:\Users\asus\Desktop\LLM\venv\lib\site-packages\huggingface_hub\file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification m

(Pipeline returns the class with the highest probability, instead of returning all possible class labels with their associated probabilities).

In [5]:

text=['iam going to the sea','i will eat candy','iam fasing issues','the weather is very nice','iam worried','iam happy']
pipe(text)

[{'label': 'neutral', 'score': 0.7834017276763916},
 {'label': 'positive', 'score': 0.4980694353580475},
 {'label': 'negative', 'score': 0.665940523147583},
 {'label': 'positive', 'score': 0.976225733757019},
 {'label': 'negative', 'score': 0.48047560453414917},
 {'label': 'positive', 'score': 0.936791718006134}]

Text Classification: Needs training on specific categories (with examples).

Zero-Shot Classification: Doesn't need training on specific categories but needs a list of possible categories to predict from.Because it understand language and the relation bween words.

In [6]:
from transformers import pipeline

# Use a well-known zero-shot classification model
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

text='i love cooking and hiking'
labels=['book','hobby','sports']
result=classifier(text, candidate_labels=labels)
result

{'sequence': 'i love cooking and hiking',
 'labels': ['hobby', 'sports', 'book'],
 'scores': [0.9825448989868164, 0.011807792820036411, 0.005647298414260149]}

In [7]:
from transformers import pipeline

# Use a well-known zero-shot classification model
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Define your input text and candidate labels
text = "I love playing football on weekends!"
candidate_labels = ["sports", "cooking", "technology"]

# Get the prediction
result = classifier(text, candidate_labels=candidate_labels)

# Print the result
print(result)



{'sequence': 'I love playing football on weekends!', 'labels': ['sports', 'technology', 'cooking'], 'scores': [0.9972600936889648, 0.0016201885882765055, 0.0011196587001904845]}


In [8]:

text=['iam going to the sea','iam fasing issues','the weather is very nice','iam worried','iam happy']
pipe(text)

[{'label': 'neutral', 'score': 0.7834017276763916},
 {'label': 'negative', 'score': 0.665940523147583},
 {'label': 'positive', 'score': 0.976225733757019},
 {'label': 'negative', 'score': 0.48047560453414917},
 {'label': 'positive', 'score': 0.936791718006134}]

In [9]:
image=pipeline(task='image-classification')
prediction=image(["llamas.webp"])
prediction


No model was supplied, defaulted to google/vit-base-patch16-224 and revision 5dca96d (https://huggingface.co/google/vit-base-patch16-224).
Using a pipeline without specifying a model name and revision in production is not recommended.


[[{'score': 0.9989421963691711, 'label': 'llama'},
  {'score': 9.738920198287815e-05,
   'label': 'Arabian camel, dromedary, Camelus dromedarius'},
  {'score': 3.741530599654652e-05, 'label': 'standard poodle'},
  {'score': 3.297920920886099e-05, 'label': 'komondor'},
  {'score': 2.4718759959796444e-05, 'label': 'ram, tup'}]]

Calsses:

In [10]:
from transformers import AutoTokenizer
modelname="cardiffnlp/twitter-roberta-base-sentiment-latest"


The auto-tokenizer breaks down the input into tokens and converts them into numerical values. Since model cannt work with text

In [11]:
tokenizer=AutoTokenizer.from_pretrained(modelname)

In [12]:
text="i want to travel,do you want to go"

12 inputs ID (cls(start of sentence), sep(end of sentence), 9 words and one for the comma)

In [13]:
encodedinput=tokenizer(text)
encodedinput

{'input_ids': [0, 118, 236, 7, 1504, 6, 5016, 47, 236, 7, 213, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [14]:
encodedinput['input_ids']

[0, 118, 236, 7, 1504, 6, 5016, 47, 236, 7, 213, 2]

In [15]:
tokenizer.vocab_size

50265

In [16]:
tokenizer.convert_ids_to_tokens(1504)

'Ġtravel'

In [17]:
newtokens=['whaleshark','unicars']
tokenizer.convert_tokens_to_ids(newtokens)

[3, 3]

In [18]:
tokenizer.convert_ids_to_tokens(3)

'<unk>'

In [19]:
tokenizer.add_tokens(new_tokens=newtokens)

2

In [20]:
tokenizer.convert_tokens_to_ids(newtokens)

[50265, 50266]

In [21]:
tokenizer.convert_ids_to_tokens(50266)

'unicars'

In [22]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

Automodel for sequence classification looks at these token IDs and make predictions(calssifiying sentiment or generating text)

In [23]:
tokenizer=tokenizer.from_pretrained(modelname)
model=AutoModelForSequenceClassification.from_pretrained(modelname)

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [24]:
model

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0): RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerN

In [64]:
text="iam very excited to go"
input=tokenizer(text,return_tensors="pt")
input

{'input_ids': tensor([[   0, 6009,  182, 2283,    7,  213,    2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}

In [65]:
input['input_ids']

tensor([[   0, 6009,  182, 2283,    7,  213,    2]])

In [66]:
tokenizer.convert_ids_to_tokens(182)

'Ġvery'

Gradient Descent is a popular optimization algorithm used in machine learning and deep learning to train models. Its purpose is to minimize the error or loss of the model by adjusting the model's parameters (like weights and biases) in the right direction.

In [ ]:
with torch.no_grad():
    output=model(**input)#** to unpack model(inputsid=  , attention_mask= )

logits: Predictions

In [68]:
output

SequenceClassifierOutput(loss=None, logits=tensor([[-2.5205, -1.1282,  3.5125]]), hidden_states=None, attentions=None)

In [69]:
score=output.logits
score

tensor([[-2.5205, -1.1282,  3.5125]])

Softmax takes a set of numbers (like scores or logits) and turns them into probabilities that sum up to 1

In [76]:
prob=torch.softmax(score,dim=1)
prob

tensor([[0.0024, 0.0095, 0.9881]])

In [77]:
from transformers import AutoConfig

In [78]:
config=AutoConfig.from_pretrained(modelname)
config

c:\Users\asus\Desktop\LLM\venv\lib\site-packages\huggingface_hub\file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


RobertaConfig {
  "_name_or_path": "cardiffnlp/twitter-roberta-base-sentiment-latest",
  "architectures": [
    "RobertaForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "negative",
    "1": "neutral",
    "2": "positive"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "negative": 0,
    "neutral": 1,
    "positive": 2
  },
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.27.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 50265
}

Autoconfig contains id2label which assing each probability to its corresponding class name.

In [81]:
for i,prob in enumerate(prob):
    label=config.id2label[i]
    print(f'{label}{prob}')

negative0.0023698718287050724
neutral0.00953624490648508
positive0.988093912601471


In sequence classification tasks (like sentiment analysis), you're not generating new text. You're classifying the input into categories.

Input: You pass the tokenized text (which is converted into token IDs) into the encoder model (e.g., BERT).

BERT (Encoder): The encoder processes the tokens, understanding the meaning and context of the input text.

Classification Head: A classification head is attached to the model. It takes the output of the encoder (the contextual embeddings) and uses them to classify the input text into predefined categories (such as "positive" or "neutral" sentiment).

Output: The model gives you the final predicted label for the text, like "positive", "neutral", or "negative".